# Generated by Django 4.1.6 on 2023-05-23 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Platillos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.CharField(default=' ', max_length=1000)),
                ('precio', models.PositiveSmallIntegerField()),
                ('categoria', models.PositiveSmallIntegerField()),
                ('imagen', models.CharField(default=' ', max_length=1000)),
            ],
        ),
    ]
