# Generated by Django 4.1.6 on 2023-05-28 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ticket', models.PositiveSmallIntegerField()),
                ('nombre', models.CharField(max_length=200)),
                ('precio', models.PositiveSmallIntegerField()),
                ('cantidad', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
